# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SG2QGIS
                                 A QGIS plugin
 A Safegraph API connector
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-25
        copyright            : (C) 2021 by Riccardo Klinger
        email                : riccardo.klinger@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Riccardo Klinger'
__date__ = '2021-04-25'
__copyright__ = '(C) 2021 by Riccardo Klinger'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SG2QGIS class from file SG2QGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sg2qgis import SG2QGISPlugin
    return SG2QGISPlugin()
